# This file contains a single comic strip definition.
# It was created by rake comics:dump and can be overwritten at any time.
# THIS FILE IS NOT DIRECTLY USED BY RUBYCOM!
# It's only purpose is to be pushed to github and then be merged
# into config/comics.yml by the maintainer of rubycom.

---
der_flix:
    name: "Der Flix"
    base_url: "http://der-flix.de/index.php"
    search_query: "td > img"

