# This file contains a single comic strip definition.
# It was created by rake comics:dump and can be overwritten at any time.
# THIS FILE IS NOT DIRECTLY USED BY RUBYCOM!
# It's only purpose is to be pushed to github and then be merged
# into config/comics.yml by the maintainer of rubycom.

---
did_you_know_gaming:
    name: "Did you know gaming"
    base_url: "http://didyouknowgaming.com/"
    search_query: ".class2 img"

