# This file contains a single comic strip definition.
# It was created by rake comics:dump and can be overwritten at any time.
# THIS FILE IS NOT DIRECTLY USED BY RUBYCOM!
# It's only purpose is to be pushed to github and then be merged
# into config/comics.yml by the maintainer of rubycom.

---
google_doodle:
    name: "Google Doodle"
    base_url: "http://www.google.com/webhp?hl=en"
    search_query: "img#hplogo"
    ignore_size: true

