# This file contains a single comic strip definition.
# It was created by rake comics:dump and can be overwritten at any time.
# THIS FILE IS NOT DIRECTLY USED BY RUBYCOM!
# It's only purpose is to be pushed to github and then be merged
# into config/comics.yml by the maintainer of rubycom.

---
scenes_from_a_multiverse:
    name: "Scenes from a Multiverse"
    base_url: "http://amultiverse.com/"
    search_query: "#comic-1 img"

