# This file contains multiple comic strip definitions.
# It is created by rake comics:merge, which merges all the definitions from
# config/comics/, which in turn are created by rake comics:dump into this file.
# This file will be kept up to date by the maintainer of this project.
# 
# This file in config/ will serve as a fallback solution for rubycom if the current
# definitions can't be downloaded from github.
# This file in tmp/ is the most recently downloaded version.

accidental_centaurs:
    name: "Accidental Centaurs"
    base_url: "http://www.accidentalcentaurs.com"
    search_query: ".webcomic-object-full img"

action_trip:
    name: "ActionTrip"
    base_url: "http://www.actiontrip.com/index/comics.phtml"
    search_query: ".comicarchiveline a; img#comic"

amazing_superpowers:
    name: "Amazing Superpowers"
    base_url: "http://www.amazingsuperpowers.com"
    search_query: "div#comic-1 img"

andy_capp:
    name: "Andy Capp"
    base_url: "http://www.creators.com/featurepages/11_comics_andy-capp.html?name=cap"
    search_query: "div#comic_full img"
    regexp_search: "&w=[0-9]+"
    regexp_replace: ""

applegeeks_lite:
    name: "Applegeeks Lite"
    base_url: "http://www.applegeeks.com/lite/"
    search_query: "div#strip img"

awkward_zombie:
    name: "Awkward Zombie"
    base_url: "http://awkwardzombie.com"
    search_query: "#comic img"

battlepug:
    name: "Battlepug"
    base_url: "http://battlepug.com"
    search_query: "#comic-1 img"

bc:
    name: "B.C."
    base_url: "http://www.creators.com/comics/bc.html?comicname=bc"
    search_query: "table[width=\"700\"] img"

beetle_bailey:
    name: "Beetle Bailey"
    base_url: "http://www.arcamax.com/thefunnies/beetlebailey"
    search_query: "article.comic a img"

beetlebum:
    name: "Beetlebum"
    base_url: "http://blog.beetlebum.de"
    search_query: "div.entry img[src]"

brawl_in_the_family:
    name: "Brawl In The Family"
    base_url: "http://brawlinthefamily.keenspot.com/"
    search_query: "div#comic img"

bug:
    name: "Bug"
    base_url: "http://www.bugcomic.com/"
    search_query: "#comic-1 img"

buttersafe:
    name: "Buttersafe"
    base_url: "http://buttersafe.com/"
    search_query: "div#comic > img"

calm_blue_oceans:
    name: "Calm Blue Oceans"
    base_url: "http://calmblueoceans.com/"
    search_query: "div.comicpane > img[src]"

calvin_and_hobbes:
    name: "Calvin and Hobbes"
    base_url: "http://www.gocomics.com/calvinandhobbes/"
    search_query: "p.feature_item img"

cleopatra_in_space:
    name: "Cleopatra in Space"
    base_url: "http://www.cowshell.com/cleopatra/"
    search_query: "div.comicpress_latest_thumbnail_widget a; div#comic-1 img"

completely_serious_comics:
    name: "Completely Serious Comics"
    base_url: "http://completelyseriouscomics.com"
    search_query: "div.comicpane img"

ctrl-alt-del:
    name: "Ctrl-Alt-Del"
    base_url: "http://www.cad-comic.com/cad"
    search_query: "div#content > img"

cyanide_and_happiness:
    name: "Cyanide and Happiness"
    base_url: "http://www.explosm.net/comics/new/"
    search_query: "div > img[alt~=Cyanide]"

der_flix:
    name: "Der Flix"
    base_url: "http://der-flix.de/index.php"
    search_query: "td > img"

did_you_know_gaming:
    name: "Did you know gaming"
    base_url: "http://didyouknowgaming.com/"
    search_query: ".class2 img"

diesel_sweeties:
    name: "diesel sweeties"
    base_url: "http://www.dieselsweeties.com/"
    search_query: "img[alt=\"newest diesel sweeties webcomic\"]"

dilbert:
    name: "Dilbert"
    base_url: "http://www.dilbert.com/strips/"
    search_query: "div.STR_Image a img"

doghouse_diaries:
    name: "Doghouse Diaries"
    base_url: "http://www.thedoghousediaries.com/"
    search_query: "img.comic-item"

dominic_deegan:
    name: "Dominic Deegan"
    base_url: "http://www.dominic-deegan.com/"
    search_query: "div.comic img"

dork_tower:
    name: "DorkTower"
    base_url: "http://www.dorktower.com"
    search_query: ".entry-content img"

dueling_analogs:
    name: "Dueling Analogs"
    base_url: "http://duelinganalogs.com"
    search_query: "div#comic img"

eat_that_toast:
    name: "Eat that Toast"
    base_url: "http://eatthattoast.com"
    search_query: "div.comicpane img"

el_goonish_shive:
    name: "El Goonish Shive"
    base_url: "http://www.egscomics.com/"
    search_query: "div.comic2 img"

endless_origami:
    name: "Endless Origami"
    base_url: "http://endlessorigami.com/"
    search_query: "div.comicpane img[src]"

extralife:
    name: "Extralife"
    base_url: "http://www.myextralife.com/"
    search_query: "div.comic-content a img"

frederik_fon_flatter:
    name: "frederik fon flatter"
    base_url: "http://www.fonflatter.de/"
    search_query: "#content > p > a > img"

garfield:
    name: "Garfield"
    base_url: "http://www.gocomics.com/garfield/"
    search_query: "p.feature_item img"

garfield_minus_garfield:
    name: "Garfield minus Garfield"
    base_url: "http://garfieldminusgarfield.net/"
    search_query: "div.photo a img"

geek_and_poke:
    name: "Geek And Poke"
    base_url: "http://geekandpoke.typepad.com/"
    search_query: "img.image-full"

google_doodle:
    name: "Google Doodle"
    base_url: "http://www.google.com/webhp?hl=en"
    search_query: "img#hplogo"
    ignore_size: true

hagar_the_horrible:
    name: "Hagar the horrible"
    base_url: "http://www.arcamax.com/thefunnies/hagarthehorrible"
    search_query: "article.comic a img"

hejibits:
    name: "Hejibits"
    base_url: "http://www.hejibits.com/"
    search_query: "div.comicpane img"

hijinks_ensue:
    name: "HijiNKS ENSUE"
    base_url: "http://hijinksensue.com/"
    search_query: "#comic-1 img"

joy_of_tech:
    name: "Joy of Tech"
    base_url: "http://www.geekculture.com/joyoftech/"
    search_query: "td[valign=top] > div[align=center] p > img"

kevin_and_kell:
    name: "Kevin and Kell"
    base_url: "http://www.kevinandkell.com/"
    search_query: "div#comic a img"

league_of_super_redundant_heroes:
    name: "League of Super Redundant Heroes"
    base_url: "http://superredundant.com/"
    search_query: "#comic-1 img"

least_i_could_do:
    name: "Least I could do"
    base_url: "http://www.leasticoulddo.com/"
    search_query: "#comic img"

little_gamers:
    name: "Little Gamers"
    base_url: "http://www.little-gamers.com/"
    search_query: "div#comic-middle img"

loading_artist:
    name: "Loading Artist"
    base_url: "http://www.loadingartist.com/"
    search_query: "div.comicpane  img"

nasa:
    name: "NASA Image of the day"
    base_url: "http://www.nasa.gov/rss/image_of_the_day.rss"
    search_query: ""

nerf_now:
    name: "Nerf Now"
    base_url: "http://www.nerfnow.com/"
    search_query: "div#comic img"

nichtlustig:
    name: "Nichtlustig"
    base_url: "http://nichtlustig.de/rss/nichtrss.rss"
    search_query: "item table img[src*=comics]"

not_invented_here:
    name: "Not invented here"
    base_url: "http://notinventedhe.re"
    search_query: "#comic-content a img"

optipess:
    name: "Optipess"
    base_url: "http://www.optipess.com/"
    search_query: "#comic-1 img"

pajama_forest:
    name: "Pajama Forest"
    base_url: "http://pajamaforest.com/"
    search_query: "div.comicpane img"

pants_are_overrated:
    name: "Pants are overrated"
    base_url: "http://www.pantsareoverrated.com/"
    search_query: "div#comic-1 img"

penny_arcade:
    name: "Penny Arcade"
    base_url: "http://www.penny-arcade.com/comic/"
    search_query: "div.post.comic img"

phd_comics:
    name: "PHD Comics"
    base_url: "http://www.phdcomics.com/comics.php"
    search_query: "td[align=\"center\"] > img[align=\"top\"]"

questionable_content:
    name: "Questionable Content"
    base_url: "http://questionablecontent.net/"
    search_query: "img#strip"

real_life:
    name: "Real Life"
    base_url: "http://www.reallifecomics.com/"
    search_query: "div.comic_image img"

reds_planet:
    name: "Red's Planet"
    base_url: "http://www.redsplanet.com/comic/"
    search_query: "#comic img"

rob_and_elliot:
    name: "Rob and Elliot"
    base_url: "http://www.robandelliot.cycomics.com/index.php"
    search_query: "#contentcomic img"

rooster_teeth:
    name: "Rooster Teeth"
    base_url: "http://roosterteeth.com/comics/today.php"
    search_query: "img.icon"

ruthe:
    name: "Ruthe"
    base_url: "http://ruthe.de/"
    search_query: "div#cartoon img"

sarah_burrini:
    name: "Sarah Burrini"
    base_url: "http://sarahburrini.com/wordpress/"
    search_query: "div.comicpane img"

scandinavia_and_the_world:
    name: "Scandinavia and the world"
    base_url: "http://satwcomic.com/"
    search_query: "center > div > a > img"

scenes_from_a_multiverse:
    name: "Scenes from a Multiverse"
    base_url: "http://amultiverse.com/"
    search_query: "#comic-1 img"

shakes_and_fidget:
    name: "Shakes & Fidget"
    base_url: "http://www.shakesandfidget.com/"
    search_query: ".widget.comicpress_latest_thumbnail_widget a; #comic-1 img"

shermans_lagoon:
    name: "Sherman's Lagoon"
    base_url: "http://www.slagoon.com/cgi-bin/sviewer.pl"
    search_query: "body > p[align=LEFT] > img"

shoeboxblog:
    name: "Shoeboxblog"
    base_url: "http://www.shoeboxblog.com/"
    search_query: "div.post_content img"

sinfest:
    name: "Sinfest"
    base_url: "http://www.sinfest.net/index.php"
    search_query: "table#AutoNumber2 p[align=center] > img"

something_of_that_ilk:
    name: "Something of that Ilk"
    base_url: "http://www.somethingofthatilk.com"
    search_query: "div.comic > img"

spinnerette:
    name: "Spinnerette"
    base_url: "http://www.spinnyverse.com/"
    search_query: "div#comic-1 a img"

sunday_morning_breakfast_cereal:
    name: "Sunday Morning Breakfast Cereal"
    base_url: "http://www.smbc-comics.com/"
    search_query: "td.comicboxcenter td > center > img:not([alt])"

the_warehouse:
    name: "The Warehouse"
    base_url: "http://www.warehousecomic.com/index.php"
    search_query: "div.comicHolder div[align=center] > img"

the_wotch:
    name: "The Wotch"
    base_url: "http://www.thewotch.com/"
    search_query: "div.comic2 img"

tot_aber_lustig:
    name: "Tot aber lustig"
    base_url: "http://www.totaberlustig.com/"
    search_query: "#comic img"

touche:
    name: "Touche"
    base_url: "http://www.taz.de/digitaz/.tom/tomdestages"
    search_query: "div.tom_content img"

twisted_speedo:
    name: "Twisted Speedo"
    base_url: "http://twistedspeedo.com/"
    search_query: "div.comicpane > img[src]"

union_der_helden:
    name: "Union der Helden"
    base_url: "http://www.unionderhelden.de"
    search_query: "div.content dl.csc-textpic-image dt img"

user_friendly:
    name: "User Friendly"
    base_url: "http://www.userfriendly.org/static/"
    search_query: "img[alt=\"Latest Strip\"]"

vg_cats:
    name: "VG Cats"
    base_url: "http://www.vgcats.com/comics/"
    search_query: "div[align=\"center\"] > img"

virtual_shackles:
    name: "Virtual Shackles"
    base_url: "http://www.virtualshackles.com/"
    search_query: "div#comicbox img"

wizard_of_id:
    name: "Wizard of Id"
    base_url: "http://www.arcamax.com/thefunnies/wizardofid"
    search_query: "article.comic a img"

wulffmorgenthaler:
    name: "Wulffmorgenthaler"
    base_url: "http://wulffmorgenthaler.com/"
    search_query: "div.stribe img"

xkcd:
    name: "XKCD"
    base_url: "http://xkcd.com"
    search_query: "div#comic img"

